##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Fri Nov 11 14:58:17 EST 2022] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# building variables
######################################
# debug build?
DEBUG ?= 1
# optimization
OPT ?= -Og

BSP ?= stm32f030cctx
BSP_PREFIX = ../bsp/$(BSP)
#######################################
# paths
#######################################
# Build path
TARGET ?= bootloader
BUILD_DIR ?= build
OUTPUT_DIR ?= out
HW_VERSION ?= 6
MKDIR = mkdir -p
export

.PHONY: all clean $(TARGET)

# default action: build all
all: $(TARGET)

$(TARGET):
	$(MKDIR) $(BUILD_DIR)
	cd $(BUILD_DIR); $(MAKE) -f ../$(TARGET)/Makefile

clean:
	$(RM) -fR $(BUILD_DIR)

# *** EOF ***
