# Major hardware revisions
HW_VERSION_MKI = 0
HW_VERSION_MKII = 4
HW_VERSION_MKIII = 8
HW_VERSION_MKIV = 9
HW_VERSION_MKV = 10

# Minor hardware revisions
HW_VERSION_MKIR1 = 0
HW_VERSION_MKIR2 = 1
HW_VERSION_MKIR3 = 2
HW_VERSION_MKIR4 = 3

HW_VERSION_MKIIR1 = 4
HW_VERSION_MKIIR1C = 5
HW_VERSION_MKIIR2 = 6
HW_VERSION_MKIIR3 = 7

HW_VERSION_MKIII = 8

HW_VERSION_MKIVR1 = 9

HW_VERSION_MKVR1 = 10
HW_VERSION_MKVR1L = 11
HW_VERSION_MAX = 12